### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by LiveLaden** [instafluff/HighlightOfMyChat#8]
The code worked for a really long time, but in the last week it stopped working, no idea why

**Comment by Vuurvos1** [comment]
Look at [issue 7]( https://github.com/instafluff/HighlightOfMyChat/issues/7) for more information

**Comment by LiveLaden** [comment]
How do I change the browser OBS Studio uses

**Comment by Vuurvos1** [comment]
You don't, you have to install the Brave browser and have it open a tab there and capture Brave instead of using a browser source. Note that this is only a temporary solution that happens to work.

**Comment by BearlyLIVE** [comment]
hi, i downloaded brave and tried it it but didn't get any sound. tried clicking the browser to activate it.

Also tried the CORS solution from the article.

Is there anything else i should be checking to get it working?

**Comment by Vuurvos1** [comment]
There are a few things you can check:

1. Are you 100% sure the URL is correct?
2. Is audio enabled in the site settings
3. Is type of reward you are using on Twitch the default hight message or a custom one (because I think it only works with the default one but not 100% sure on that)

Apart from those things, I have no clue.

**Comment by instafluff** [comment]
It should work now thanks to @Vuurvos1 with 9eea3c7e26858e84bd0e2558d8a17d310ba94de9 !
